import { Schema } from 'effect';
import { DateFieldSchema, decodeKintoneRecord, NumberFieldSchema, SingleLineTextFieldSchema } from 'kintone-effect-schema';

// Static record schema generated from form definition
export const RecordSchema = Schema.Struct({
  field_0: NumberFieldSchema,
  field_1: DateFieldSchema,
  field_2: SingleLineTextFieldSchema,
  field_3: NumberFieldSchema,
  field_4: DateFieldSchema,
  field_5: SingleLineTextFieldSchema,
  field_6: NumberFieldSchema,
  field_7: DateFieldSchema,
  field_8: SingleLineTextFieldSchema,
  field_9: NumberFieldSchema,
  field_10: DateFieldSchema,
  field_11: SingleLineTextFieldSchema,
  field_12: NumberFieldSchema,
  field_13: DateFieldSchema,
  field_14: SingleLineTextFieldSchema,
  field_15: NumberFieldSchema,
  field_16: DateFieldSchema,
  field_17: SingleLineTextFieldSchema,
  field_18: NumberFieldSchema,
  field_19: DateFieldSchema,
  field_20: SingleLineTextFieldSchema,
  field_21: NumberFieldSchema,
  field_22: DateFieldSchema,
  field_23: SingleLineTextFieldSchema,
  field_24: NumberFieldSchema,
  field_25: DateFieldSchema,
  field_26: SingleLineTextFieldSchema,
  field_27: NumberFieldSchema,
  field_28: DateFieldSchema,
  field_29: SingleLineTextFieldSchema,
  field_30: NumberFieldSchema,
  field_31: DateFieldSchema,
  field_32: SingleLineTextFieldSchema,
  field_33: NumberFieldSchema,
  field_34: DateFieldSchema,
  field_35: SingleLineTextFieldSchema,
  field_36: NumberFieldSchema,
  field_37: DateFieldSchema,
  field_38: SingleLineTextFieldSchema,
  field_39: NumberFieldSchema,
  field_40: DateFieldSchema,
  field_41: SingleLineTextFieldSchema,
  field_42: NumberFieldSchema,
  field_43: DateFieldSchema,
  field_44: SingleLineTextFieldSchema,
  field_45: NumberFieldSchema,
  field_46: DateFieldSchema,
  field_47: SingleLineTextFieldSchema,
  field_48: NumberFieldSchema,
  field_49: DateFieldSchema,
  field_50: SingleLineTextFieldSchema,
  field_51: NumberFieldSchema,
  field_52: DateFieldSchema,
  field_53: SingleLineTextFieldSchema,
  field_54: NumberFieldSchema,
  field_55: DateFieldSchema,
  field_56: SingleLineTextFieldSchema,
  field_57: NumberFieldSchema,
  field_58: DateFieldSchema,
  field_59: SingleLineTextFieldSchema,
  field_60: NumberFieldSchema,
  field_61: DateFieldSchema,
  field_62: SingleLineTextFieldSchema,
  field_63: NumberFieldSchema,
  field_64: DateFieldSchema,
  field_65: SingleLineTextFieldSchema,
  field_66: NumberFieldSchema,
  field_67: DateFieldSchema,
  field_68: SingleLineTextFieldSchema,
  field_69: NumberFieldSchema,
  field_70: DateFieldSchema,
  field_71: SingleLineTextFieldSchema,
  field_72: NumberFieldSchema,
  field_73: DateFieldSchema,
  field_74: SingleLineTextFieldSchema,
  field_75: NumberFieldSchema,
  field_76: DateFieldSchema,
  field_77: SingleLineTextFieldSchema,
  field_78: NumberFieldSchema,
  field_79: DateFieldSchema,
  field_80: SingleLineTextFieldSchema,
  field_81: NumberFieldSchema,
  field_82: DateFieldSchema,
  field_83: SingleLineTextFieldSchema,
  field_84: NumberFieldSchema,
  field_85: DateFieldSchema,
  field_86: SingleLineTextFieldSchema,
  field_87: NumberFieldSchema,
  field_88: DateFieldSchema,
  field_89: SingleLineTextFieldSchema,
  field_90: NumberFieldSchema,
  field_91: DateFieldSchema,
  field_92: SingleLineTextFieldSchema,
  field_93: NumberFieldSchema,
  field_94: DateFieldSchema,
  field_95: SingleLineTextFieldSchema,
  field_96: NumberFieldSchema,
  field_97: DateFieldSchema,
  field_98: SingleLineTextFieldSchema,
  field_99: NumberFieldSchema
});

export type AppRecord = Schema.Schema.Type<typeof RecordSchema>;
export type AppRecordEncoded = Schema.Schema.Encoded<typeof RecordSchema>;

export const validateRecord = (record: Record<string, unknown>): AppRecord => {
  const normalizedRecord = decodeKintoneRecord(record);
  return Schema.decodeUnknownSync(RecordSchema)(normalizedRecord);
};
