// App fields configuration type (generated by kintone-effect-schema)
export interface AppFieldsConfig {
  properties: Record<string, any>;
}

// App schema definition
export interface AppSchema {
  appId: number | string;
  name: string;
  description?: string;
  fieldsConfig: AppFieldsConfig;
}

// Auth configuration types
export interface PasswordAuth {
  baseUrl: string;
  username: string;
  password: string;
}

export interface ApiTokenAuth {
  baseUrl: string;
  apiToken: string;
}

export type AuthConfig = PasswordAuth | ApiTokenAuth;

// Environment configuration
export interface EnvironmentConfig {
  auth: AuthConfig;
}

// Main configuration
export interface Config {
  default: string;
  environments: Record<string, EnvironmentConfig>;
}

// Helper function to define app schema
export function defineAppSchema(schema: AppSchema): AppSchema {
  return schema;
}

// Helper function to get app ID from environment variable
export function getAppId(envVarName: string): string {
  const appId = process.env[envVarName];
  if (!appId) {
    throw new Error(`Environment variable ${envVarName} is not set`);
  }
  return appId;
}